algoritmo carro
	literal modelo
	inteiro quilometragem
	real valor
	inicio
		escreva("Digite o modelo do veículo: ")
		leia(modelo)
		escreva("Digite a quilometragem do veículo: ")
		leia(quilometragem)
		escreva("Digite o valor do veículo: ")
		leia(valor)
		escreva("Dados do veículo: \n Modelo: " +
                    modelo +"\n Quilometragem: " +
                    quilometragem + "km\n Valor: R$ " + valor))
	fim 
	
	